extends: 'kitti_base.yaml'

identifier: kitti_00-10

data:
  training: ['${KITTI_PATH}/odometry/00.lmdb',
             '${KITTI_PATH}/odometry/01.lmdb',
             '${KITTI_PATH}/odometry/02.lmdb',
             '${KITTI_PATH}/odometry/03.lmdb',
             '${KITTI_PATH}/odometry/04.lmdb',
             '${KITTI_PATH}/odometry/05.lmdb',
             '${KITTI_PATH}/odometry/06.lmdb',
             '${KITTI_PATH}/odometry/07.lmdb',
             '${KITTI_PATH}/odometry/08.lmdb',
             '${KITTI_PATH}/odometry/09.lmdb',
             '${KITTI_PATH}/odometry/10.lmdb']
  validation: ['${KITTI_PATH}/odometry/04.lmdb',
               '${KITTI_PATH}/odometry/10.lmdb']
  dataset_type: kitti_odometry_velodyne
  sequential: True

transforms:
  point_noise:
    type: normal
    scale: 0.01
  translation_noise:
    type: normal
    scale: [0.2, 0.02, 0.02]
  rotation_noise_deg:
    type: normal
    scale: [0.1, 0.1, 1.0]
